name: My workflow

on:
  push:
    branches: [ master ]

jobs:
  my-job:
    name: My job
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to ${{ secrets.SURGE_DOMAIN }}
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: ${{ secrets.SURGE_DOMAIN }}
          project: './dist'
          login: ${{ secrets.SURGE_LOGIN }}
          token: ${{ secrets.SURGE_TOKEN }}
